In [1]:
import os

In [2]:
import pandas as pd

In [3]:
LOG_FILE_NAME = "experiment-logs.jsonl"

In [4]:
def load_file(path: str, name: str = LOG_FILE_NAME) -> pd.DataFrame:
    return pd.read_json(os.path.join(path, name), lines=True)

In [5]:
load_file("/Users/guilherme/fs/drmdp/control/hc/1777028923/")

   episode  steps    returns                       info
0       10   2500 -92.354578  {'hc_total_steps': 25000}
1       20    421  81.697068  {'hc_total_steps': 38572}

In [6]:
load_file("/Users/guilherme/fs/drmdp/control/dgra/1777030911/")

   episode  steps   returns                                               info
0       10   2500 -2.585155  {'sac_total_steps': 25000, 'reward_model_total...
1       20   2500 -1.939668  {'sac_total_steps': 50000, 'reward_model_total...

In [7]:
load_file("/Users/guilherme/fs/drmdp/control/dgra/1777033968")["info"][0]

{'sac_total_steps': 25000,
 'reward_model_total_steps': 1981,
 'delayed_returns': -0.09604094725557501,
 'estimated_return': -2.448102235794067,
 'reward_model': {'buffer_size': 142.0,
  'training_steps': 424.0,
  'reward_loss': 3.6775514781576625e-08,
  'regu_loss': 3.677472607913993e-08}}

In [8]:
load_file("/Users/guilherme/fs/drmdp/control/dgra/1777041442/")

,episode,steps,global_steps,returns,info
0,4,2500,10000,-60.206234,"{'sac_total_steps': 10000, 'reward_model_total..."
1,8,2500,20000,-6.338233,"{'sac_total_steps': 20000, 'reward_model_total..."
2,12,2500,30000,-2.019792,"{'sac_total_steps': 30000, 'reward_model_total..."
3,16,2500,40000,-1.984682,"{'sac_total_steps': 40000, 'reward_model_total..."
4,20,2500,50000,-1.953463,"{'sac_total_steps': 50000, 'reward_model_total..."

In [9]:
load_file("/Users/guilherme/fs/drmdp/control/delayed/1777045531/")

,episode,steps,global_steps,returns,info
0,4,2500,10000,-87.679361,"{'total_steps': 10000, 'delayed_returns': -1.4..."
1,9,2500,22229,-84.199815,"{'total_steps': 22229, 'delayed_returns': 0.0,..."
2,13,2500,32229,-61.242208,"{'total_steps': 32229, 'delayed_returns': -6.2..."
3,18,2500,44508,-109.364169,"{'total_steps': 44508, 'delayed_returns': -13...."

In [10]:
load_file("/Users/guilherme/fs/drmdp/control/delayed/1777049664/")

,episode,steps,global_steps,returns,info
0,4,2500,10000,-84.857713,"{'total_steps': 10000, 'delayed_returns': -3.0..."
1,16,640,20195,74.843621,"{'total_steps': 20195, 'delayed_returns': -0.4..."
2,20,2500,30195,-98.437819,"{'total_steps': 30195, 'delayed_returns': -6.8..."
3,25,2500,40568,-81.997992,"{'total_steps': 40568, 'delayed_returns': -3.8..."